### PR TITLE
Set max_num_pages inside WP_Query

### PR DESCRIPTION
**Pull request by sboisvert**
Set max_num_pages inside WP_Query since without it some pagination will break. Internal #51345

### CODE REVIEW

**Comment by mboynes** [comment]
Thanks! Do you have an example where this might've broken something? I'd love to have a unit test around that issue

**Comment by kasparsd** [comment]
@mboynes Missing `max_num_pages` breaks all instances of pagination which relies on it for the total number of pages. See [`paginate_links()`](https://github.com/WordPress/WordPress/blob/fe3b007fdd41afa8a7fe104f4a14bce3761e98ce/wp-includes/general-template.php#L3034) for example. WP_Query sets the `max_num_pages` [during `set_found_posts()`](https://github.com/WordPress/WordPress/blob/fe3b007fdd41afa8a7fe104f4a14bce3761e98ce/wp-includes/query.php#L3837).

**Comment by kasparsd** [comment]
@mboynes I was wondering if you had a chance to look at the example and details I provided? Thank you.

**Comment by dero** [comment]
@mboynes Have you had the chance to review the information provided by @sboisvert and @kasparsd? The change is very simple and it fixes a moderately serious issue with the plugin. It's also been almost two months since it was reported, so I wonder if there's more information or code we could provide to move this forward. Thanks!

**Comment by gudmdharalds** [comment]
Is it possible to have this merged?

**Comment by mboynes** [comment]
Sorry for the delay!

**Pull request merged**
