### PR TITLE
Sync with A8C forked version

### PR DESCRIPTION
**Pull request by rebeccahum**
This PR:
- Adds new adapter for VIP Search
- Syncs change from https://github.com/Automattic/vip-go-mu-plugins/pull/2635
- Syncs change from https://github.com/Automattic/es-wp-query/pull/6

### CODE REVIEW

**Comment by rebeccahum** [comment]
Ahhh wrong repo, sorry.

**Comment by mboynes** [comment]
@rebeccahum I'm happy to merge in any of this if it makes sense? At a glance it looks like valuable updates.

**Comment by rebeccahum** [comment]
@mboynes Cool, I can re-open it then!

**Comment by mboynes** [comment]
Thanks!

**Pull request merged**
